### ISSUE TITLE
MBTiles creation doesn't work

### ISSUE THREAD

**Issue by ajashton** [mapbox/mbutil#13]
At first I thought it was just because x & y were reversed, but my [theoretical solution](https://gist.github.com/866259) still isn't giving mbtiles that can be viewed in tilestream (though they seem ok from sqlite3?)

**Comment by F3L1X79** [comment]
@maply-dev I'd like to do so, but where do you make such changes?

**Comment by marco-piccolino** [comment]
@F3L1X79 you need to write a script which loops over the tiles folders

**Comment by F3L1X79** [comment]
Well, thank you for answering me! I don't know if I was clear on what I want.

I have created a .mbtiles file with TileMill, and I need tiles folders (xyz) to read it with OpenLayers3.

I'm actually using mbUtils to generate those folders, but the subfolders y and the files z.png seem to be not geolocated. Is it possible to use a projection (like EPSG:3857) when creating the folders and tiles at the good location like it is done when using gdal2tiles on a raster file?
Or is this feature not supported by mbUtils?

**Comment by marco-piccolino** [comment]
I am no expert and haven't used the tool in a while,
but I *think* WGS84 (3857) is the only proj which is supported by that
format, and x,y,z do actually contain the location information as they
represent specific quadrants on the globe in that specific projection.

2017-07-04 11:59 GMT+02:00 Félix Chrétien <notifications@github.com>:

**Comment by F3L1X79** [comment]
Ok sorry, it is working well with the good projection! It was just my local web-server which was not strong enough to load an entire map of the world and was crashing silently...
Anyway thank you for answering me!!
