### ISSUE TITLE
Export to other format than png doesnt work

### ISSUE THREAD

**Issue by wirthual** [mapbox/mbutil#61]
mb-util ~/Desktop/Leaflet/hh.mbtiles ~/Desktop/Leaflet/Test2 --image_format jpg

Creates files with the extension .jpg but they are no jpegs. 
![screenshot from 2014-12-24 14 56 20](https://cloud.githubusercontent.com/assets/2640499/5548899/0da59046-8b7d-11e4-9fd7-157619dd4d32.png)

If you rename the files to .png they work.

**Comment by johndpope** [comment]
the data in sqlite is png to begin with - 
you need to use something like imagemagick to convert https://github.com/icetan/sqlitepipe

UPDATE images SET tile_data=pipe('convert -format jpg -quality 90% png:- jpg:-', tile_data);
VACUUM images;

**Comment by tmcw** [comment]
Thanks for the question! Since this is a common question, I've added it to the FAQ: [can mbutil convert image formats?](https://github.com/mapbox/mbutil/wiki#can-mbutil-export-tiles-stored-as-jpeg-to-png-files)
