### ISSUE TITLE
Don't output debug log by default

### ISSUE THREAD

**Issue by rutsky** [mapbox/mbutil#63]
Debug output is too verbose, I suggest to add option like `-v` ("verbose") or `-d` ("debug") and only with it use DEBUG logging level.

**Comment by slongberry** [comment]
I have a fork that I changed the default log level to INFO and added a --log_level parameter to allow the user to specify the amount of detail they would like to see (DEBUG, INFO or WARNING). I found this useful when dealing with very large file based tile caches. I can submit a pull request if that would help.

**Comment by tmcw** [comment]
Happy to accept a PR implementing this change!
