### ISSUE TITLE
RFE: import directory with PNG **and** JPEG files into single MBTiles database

### ISSUE THREAD

**Issue by rutsky** [mapbox/mbutil#64]
Not sure is MBTiles authors intendent to store different types of images in single MBTiles database, but we store tiles with alpha in PNG format, and other tiles in JPEG format (since out data is orthophoto imagery that may be and better to be stored in lossy format).
So for me it would be better to specify list of acceptable image formats in `--image_format` argument.

**Comment by rowan-OzRunways** [comment]
+1 for this request!

**Comment by sgillies** [comment]
The MBTiles spec only supports a single format in a database.
