### ISSUE TITLE
Tiles all corrupt when exporting from mbtiles created in Mapbox Studio

### ISSUE THREAD

**Issue by jsweet83** [mapbox/mbutil#65]
I added a geotiff to a Mapbox Studio project, created an mbtiles file from it, and when I tried to export this to tiles, every image was corrupt.  I tried a different geotiff with the same result.  It didn't matter if my image_format was jpg or png, still the same problem.  Any ideas?

**Comment by emamd** [comment]
I'm running into this exact same problem - geotiff saved from QGIS and exported into Mapbox Studio, created an mbtiles file, and trying to export this to tiles. 

Oddly, the tiles do seem to display in Chrome on Ubuntu, but will not open in Firefox or ImageViewer.

**Comment by emamd** [comment]
@jsweet83 the tiles displayed just fine if I imported the geotiff and exported tiles using TileMill instead of Mapbox Studio. Must be something about how Mapbox Studio uses vector tiles, I imagine.

**Comment by nrakochy** [comment]
+1 Running in this as well

**Comment by Eng3l** [comment]
I got the same problem with mbtiles downloaded from [osm2vectorlines](http://osm2vectortiles.org/downloads/)

**Comment by tmcw** [comment]
Thanks for the question! Since this is a common question, I've added it to the FAQ: [Can mbutil convert image formats?](https://github.com/mapbox/mbutil/wiki#can-mbutil-export-tiles-stored-as-jpeg-to-png-files)

**Comment by nfarran** [comment]
Create tiles from image and show that tiles on leaflet map

https://youtu.be/DSu8BYtuWMU
