### ISSUE TITLE
mbutil not Exporting using bbox

### ISSUE THREAD

**Issue by ashutoshkrsng** [mapbox/mbutil#69]
can mbtiles be used to export tiles in a particular extent? I am doing the same thing using bbox but it is exporting all the tiles but not in the particular extent. 

let us know the use of bbox and tile_bbox in mbutil or how can we export tiles in particular extent.

**Comment by tmcw** [comment]
Sorry, mbutil does not support a bbox option. Happy to accept a PR if that's something you'd like to implement!
