### ISSUE TITLE
Invalid raster file when using mb-util on mbtiles of http://osm2vectortiles.org/downloads

### ISSUE THREAD

**Issue by nouryf** [mapbox/mbutil#70]
Hi,

I downloaded https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/zurich.mbtiles
and used mb-util to produce invalid png ! Does mb-util support only raster mbtiles ? or may be the .mbtiles at http://osm2vectortiles.org/ are not supported some how ?

Thanks

Noury

**Comment by MBalazs90** [comment]
Same problem here. The produced png-s are invalid! I downloaded the .mbtiles from osm2vectortiles

**Comment by vespakoen** [comment]
You cannot export them as pngs, you have to use the pbf format.

```
./mb-util --image_format=pbf zurich.mbtiles zurich
```

**Comment by nouryf** [comment]
Thanks for your response. Yes but that create .pbf format files not png. I tried jpg format and the issue is the same there as it's with png: invalid images. Does the tool does not support producing valid png or may be the referenced .mbtiles file is incorrect or not supported ?

**Comment by tmcw** [comment]
Thanks for the question! Since this is a common question, I've added it to the FAQ: [Can mbutil convert pbf or mvt (vector tiles) to images?](https://github.com/mapbox/mbutil/wiki#can-mbutil-convert-pbf-or-mvt-vector-tiles-to-images)
