### ISSUE TITLE
Usable as a library?

### ISSUE THREAD

**Issue by StyXman** [mapbox/mbutil#71]
I would like to use this code as a Python module to enable MBTiles writing to a tool I use to render tilesets. The problem is that some parts of the module (all inside the `mbutil` directory) is assuming it's only part of the `mb-util` script. For instance:

https://github.com/mapbox/mbutil/blob/master/mbutil/util.py#L41

This should be handled in the util's code. Probably others are to follow.

On the other hand, there are no functions to be able to read/write individual tiles, which could be refactored from the current code. 

I plan to start a PR soon, but I would like to hear your opinions on this.

**Comment by tmcw** [comment]
Happy to accept a PR implementing a change that would make this usable as a library!

**Comment by tmcw** [comment]
Closing; happy to accept a PR.
