### ISSUE TITLE
Please i had this errror, what shouyld i do ?? thank you for answering 

### ISSUE THREAD

**Issue by LamraniOthmane** [mapbox/mbutil#80]
![sdsd](https://cloud.githubusercontent.com/assets/26097552/23548307/c264c8ba-fffe-11e6-8f05-5a29058201b9.PNG)

**Comment by andrewharvey** [comment]
The patch utility requires the sqlite3 command line program, see https://sqlite.org/cli.html which you can install via https://sqlite.org/download.html.
