### ISSUE TITLE
Gzip format 

### ISSUE THREAD

**Issue by aarohipalkar** [mapbox/mbutil#88]
When I download MBTiles from OpenMapTiles, all the .png files that are produced after conversion are in gzip format, and I am unable to open them. However, when I create my own tiles using TileMill, mbutil works fine. Is this a common problem, and what can I do to fix this?

**Comment by ericfischer** [comment]
The OpenMapTiles downloads are tilesets of vector tiles, not tilesets of images. To view them you'll have to style them in Mapbox Studio or [using the OpenMapTiles instructions](https://openmaptiles.org/docs/).
