### ISSUE TITLE
Cannot open the exported png files.

### ISSUE THREAD

**Issue by mcorovei** [mapbox/mbutil#90]
I am using MacOS and I get this message: The file "3320.png" could not be opened. It may be damaged or use a file format that Preview doesn't recognize. when I run the application in the terminal.

**Comment by puntubabu** [comment]
I am also experiencing this issue. I need the tiles to be available offline on desktop, so I am generating the PNG's. All of the generated PNG's are damaged and unable to be opened. I am using macOS 10.16.2.

**Comment by nicooprat** [comment]
Same issue. Mac 10.12.6. Python 2.7.10.

**Comment by nicooprat** [comment]
Chrome seems to be able to open them, but Mac Preview, Firefox, Safari and so on can't. Same problem with JPGs.

**Comment by sgillies** [comment]
@nicooprat @puntubabu @mcorovei If Preview can't open them, it's possible (maybe even likely) that the images in the mbtiles file are not PNG or JPEG but WebP. Reminder: the imagery is already encoded in some format in the mbtiles file and the mbutil program only reads those out as they are encoded, it does not reformat them. Can you check the documentation of your mbtiles sources and report back here?

**Comment by nicooprat** [comment]
Looks like you're right! I'll try to convert them back to jpg or png...

![capture d ecran 2017-09-27 a 17 37 46](https://user-images.githubusercontent.com/645641/30922858-a6748c8a-a3aa-11e7-9c35-67fa06645cba.jpg)

**Comment by nicooprat** [comment]
To convert to png, the official webp command can do it: https://www.npmjs.com/package/dwebp-bin.

To convert them to jpg: `find ./ -name "*.webp" -exec ffmpeg -i {} {}.jpg \;` (need to install ffmpeg first). Had to batch rename files then: `find . -exec rename 's|.webp.jpg|.jpg|' {} +` (rename is a Mac specific command).

**Comment by sgillies** [comment]
I'll give @mcorovei a few days to reply to find out if this is the same issue before closing this.

**Comment by puntubabu** [comment]
my issue extends a step back to Tilemill and Mapbox Studio Classic. When using either program (I imagine the export engine is the same), when I export tiles to mbtiles, the "Preview" is always jacked up, but my map looks fine in Tilemill.
Here's what it looks like when I'm exporting:
![screen shot 2017-09-27 at 12 11 17 pm](https://user-images.githubusercontent.com/1911931/30927190-4dc55196-a37d-11e7-88c1-425854242098.png)

And here's what it looks like when I preview the exported mbtiles:
![screen shot 2017-09-27 at 12 12 37 pm](https://user-images.githubusercontent.com/1911931/30927209-5bedfd22-a37d-11e7-80cc-5d9257fe8d77.png)

And then, of course, when using mbutil to create the png's, they're all broken.

Have any of you guys experienced this issue with Mapbox Studio Classic / Tilemill? What program do you guys use to create mbtiles?

**Comment by sgillies** [comment]
This seems to be resolved. We can reopen if needed.
