### ISSUE TITLE
Trouble merging mbTiles

### ISSUE THREAD

**Issue by asecondwill** [mapbox/mbutil#91]
Trying to merge two mbTiles files 

````
mbtilesforthewin ❯ patch cornwall.mbtiles demo.mbtiles                                                                          ⏎
patch unexpectedly ends in middle of line
(Stripping trailing CRs from patch.)
?
````

Is this still the way to do it? Have i done part of it wrong ?

Thanks for any help

**Comment by ericfischer** [comment]
The `patch` command merges text files with the output of `diff`, not mbtiles files.

You can use `tile-count` from [Tippecanoe](https://github.com/mapbox/tippecanoe/) to merge vector tilesets.

**Comment by asecondwill** [comment]
@ericfischer  - thank you
